import { Rajdhani } from "next/font/google";
import "./_assets/globals.css";

const rajdhani = Rajdhani({
  subsets: [],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Footgoal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rajdhani.className}>
        {children}
      </body>
    </html>
  );
}
